### ISSUE TITLE
Does not remap properly when shading non-remapped module into supposed to remapped module.

### ISSUE THREAD

**Issue by portlek** [Alvinn8/paper-nms-maven-plugin#16]
Reproduce:
- Create a maven project.
- Create 2 sub module called 'api' and 'plugin'.
- Add remap support for 'plugin' module.
- Implement 'api' module into 'plugin' module.
- Add support shade plugin for 'plugin' module.
- Add some NMS related code into 'api' module.
  - Add an interface that looks like this:
    ```java
    public interface Test {
      @NotNull
      Rotations test();
    }
    ```
- Use these codes in 'plugin' module.
  - Add an implementation class for 'Test' class:
    ```java
    public final class TestImpl {
      private final Rotations test;

      public TestImpl(final Rotations test) {
        this.test = test;
      }

      @Override
      public Rotations test() {
        return this.test;
      }
    }
    ```
- Build the project using 'mvn package' command.

Actual Result:
- You will see 'plugin's implementation class will be remapped:
  ```java
  public final class TestImpl {  
    private final Vector3f test;

    public TestImpl(final Vector3f test) {
      this.test = test;
    }
    
    @Override
    public Vector3f test() {
      return this.test;
    }
  }
  ```
- You will see the shaded code that comes from 'api' module in the paper module's jar won't be remapped.
  ```java
  public interface Test {
    @NotNull
    Rotations test();
  }
  ```

Expected Result:
- The final shaded paper module's jar file has been remapped properly.

How do you think we can solve this:
- Make [inputPath](https://github.com/Alvinn8/paper-nms-maven-plugin/blob/main/src/main/java/ca/bkaw/papernmsmavenplugin/RemapMojo.java#LL29C19-L29C19) configurable.
- Add shade plugin support.
- Make [classpath](https://github.com/Alvinn8/paper-nms-maven-plugin/blob/main/src/main/java/ca/bkaw/papernmsmavenplugin/RemapMojo.java#L56) configurable.

I think shaded codes that come from any other modules won't be remapped. So, you may ask why you don't add remap support for 'api' module too? Well, i did, and it does not even build. It prints an error about interface has Vector3f method, but you didn't implement in TestImpl class. This is because of the order of the compiling classes. api -> compiled and remapped. paper -> tries to compile but Test interface has remapped code and i didn't even get the point where i remapped my paper module's code so paper module cannot know where Vector3f comes from. So, the project structure has to be like that.

**Comment by Alvinn8** [comment]
Thanks for the thorough bug report, and sorry for not reaching out sooner. I experimented a bit and found a solution to the issue. It is possible to use this plugin to remap jar files instead of class files, so you can make it remap the entire shaded jar. In the `api` module, remove the `executions` part of the plugin configuration so that it doesn't remap that module. In the `plugin` module, change the remap goal to run during the `package` phase instead of `process-classes`, and make sure the paper-nms-maven-plugin is located after the maven-shade-plugin. That way this plugin will remap the jar file after it has been shaded, and all shaded dependencies will also be remapped.
