### ISSUE TITLE
Question: Mixin compatibility

### ISSUE THREAD

**Issue by BoBkiNN** [Alvinn8/paper-nms-maven-plugin#18]
Does plugin can generate refmaps? I want to use it with mixins.

**Comment by Alvinn8** [comment]
Hello! This plugin doesn’t currently generate refmaps. I would need to look into how that works since I haven’t looked into the internals of mixins very much, and I don’t really know what a refmap is or how to generate it to be honest. There was a pull request, #12 that attempted to add support for remapping mixins, but I did really like how it had to generate mappings manually every time. Since you are the second person to ask about this there seems to be demand for it, so I could maybe look into it and see if there is a way to create this refmap file with the data the plugin already has access to.

**Comment by BoBkiNN** [comment]
Thanks for answer. I just wanted to use mixins on paper using ignite launcher without `remap=false`
