### ISSUE TITLE
Repository Authentication

### ISSUE THREAD

**Issue by TehNeon** [Alvinn8/paper-nms-maven-plugin#20]
When you're using a custom fork, you're unable to use a repository that has authentication. There isn't a way currently to specify the authentication credentials.

**Comment by Alvinn8** [comment]
Hello @TehNeon, thanks for the issue. Could you try version `1.4.2-SNAPSHOT` and instead of specifying the URL in the paper-nms-maven-plugin's devBundle configuration, specify an `id` and configure the repository in the `repositories` tag of your pom.xml. You should be able to configure authentication there if I understand it correctly. To be honest I've never used authentication on repos before so I don't really know how it's done. I'll also try to set up a local repo with auth to test, but if you already have that set up feel free to try it out.

**Comment by TehNeon** [comment]
I do happen to have a repository with authentication to test this against, and while testing, it appears now it's not seeing the repository at all.  While looking at the changes you made, it appears when there is an existing remote repository it does nothing now. I think you may have forgotten to add the remote repository to the repositories list.

**Comment by Alvinn8** [comment]
You're totally right, that's silly. I thought I tested it to make sure I didn't break anything :sweat_smile: Try again in a few minutes when the build finishes 🙂

**Comment by TehNeon** [comment]
That fixed the issue! Thank you!

**Comment by Alvinn8** [comment]
Great! Thanks for your help. I'll push the changes as version `1.4.2`.
