### ISSUE TITLE
Warning for cve

### ISSUE THREAD

**Issue by Doc94** [Alvinn8/paper-nms-maven-plugin#21]
Its a little anoying see the warning in the IDE for old CVE related to COMMONS-CODEC in dependency.
in teory that was fixed many versions ago.
![image](https://github.com/Alvinn8/paper-nms-maven-plugin/assets/3602279/6910d265-54ad-4ffb-ab25-ecd03dac6860)

**Comment by Alvinn8** [comment]
That seems like a library that Spigot includes (through `maven-resolver-transport-http`). This plugin exposes the jar with internals from the paper dev bundle as is, so I don't know if there is any appropriate fix for this from the paper-nms-maven-plugin's side since that would have to involve changing what dependencies the server jar has if that makes sense.
